server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pci_core?useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: "127.0.0.1"
    port: 6379
    password:
    #连接超时时间（毫秒）
    timeout: 3000ms
    #连接第几个数据库，默认第0个
    database: 0
    #连接池设置
    lettuce:
      pool:
        ## 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为0
        min-idle: 0

