
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pci_core?useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8080